### ISSUE TITLE
Compiler error on Debian Wheezy

### ISSUE THREAD

**Issue by exemd** [manicdigger/manicdigger#126]
error about common packet serialize
monodevelop

**Comment by croxxx** [comment]
This issue is specific to MonoDevelop, it seems.
It is caused by ManicDiggerLib project having **.NET 3.5** as target framework, whereas main application just has **.NET 2.0**.
```xml
<TargetFrameworkVersion>v3.5</TargetFrameworkVersion>
```
Probably introduced when refactoring was done:
https://github.com/manicdigger/manicdigger/blame/master/ManicDiggerLib/ManicDiggerLib.csproj

Removing the line lets MonoDevelop compile MD just fine (Tested on Debian 8)
